### PR TITLE
Some cleanup

### PR DESCRIPTION
**Pull request by Thorium**
Some cleanup:
- Removed binaries from repository
- Converted to paket. 
- Upgraded to F# 4.0.  
- Added NuGet xunit.runner.visualstudio to run tests on Visual Studio Test Explorer.

### CODE REVIEW

**Comment by Thorium** [comment]
This works very well... but with the latest references (that you can try by `.paket\paket.exe update` or `mono /.paket/paket.exe update` 

```
* FAKE 4.9.3 -> 4.39.0
* FsCheck 2.2.2 -> 2.6.0
* FsCheck.Xunit 2.2.2 -> 2.6.0
* FSharp.Core 3.1.2.5 -> 4.0.0.1
* Unquote 3.0 -> 3.1.2
```

...the system is not working any more. This is nothing to do with this commit. I think that the problem is with FsCheck.Xunit 2.6.
- Fake build script fails.
- Visual Studio Test Explorer doesn't find the tests

**Comment by ploeh** [comment]
Thank you for your interest in this example code. I hope you found it useful as a starting point.

When things don't work after updating NuGet packages, it's usually caused by assembly versioning issues. These can usually be addressed with binding redirects. IIRC, _paket_ can help you with this, but you have to tell it. Due to the size of this pull request, however, GitHub isn't showing me all the files, so I can't see your `paket.dependencies` file...

If you want to use Visual Studio Test Explorer, I think you need to add a particular NuGet package in order to enable xUnit.net discovery. Since I don't use Visual Studio Test Explorer, I can't remember the exact details, but it should be fairly easy to find documentation about this elsewhere. It oughtn't be related to FsCheck, but to xUnit.net...

If there are specific questions regarding these issues that I can answer, I'd be happy to help.

**Comment by Thorium** [comment]
Thanks for quick response!

> When things don't work after updating NuGet packages, it's usually caused by assembly versioning issues. 

Well, here the problem wasn't binding redirects, but that a) reference packages interfaces have been changed, b) some other problem with the source code of the new package components. You  can see the version in my fork but there is nothing interesting as the functionality is not changed and I expect you'll face the same errors if you ever update your version to FsCheck 2.6 via NuGet.

> If you want to use Visual Studio Test Explorer, I think you need to add a particular NuGet package

This is what I have also done already in my fork. I think the problem is that while xUnit finds `[<Fact>]` attributes from different kind of shaped test class structures (meaning your test fixture container can be a record, class, static class, or whatever), the FsCheck.xUnit `[<Property>]` is not found so many different structures...?

**Comment by ploeh** [comment]
I tried updating some of the packages using the NuGet package manager console, and as expected, `FsCheck`'s dependency on `FSharp.Core` is what causes the problem.

So I updated `FSharp.Core` as well, and updated the binding redirect:

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="FSharp.Core" publicKeyToken="b03f5f7f11d50a3a" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-4.4.0.0" newVersion="4.4.0.0" />
      </dependentAssembly>
    </assemblyBinding>
  </runtime>
</configuration>
```

With that redirect, this configuration of packages works well:

```
Id                                  Versions 
--                                  -------- 
FAKE                                {4.9.3}  
FsCheck                             {2.6.0}  
FsCheck.Xunit                       {2.6.0}  
FSharp.Core                         {4.0.1.5}
Unquote                             {3.1.2}  
xunit.abstractions                  {2.0.0}  
xunit.extensibility.core            {2.1.0}  
xunit.extensibility.execution       {2.1.0}  
xunit.runner.console                {2.1.0}  
```

**Comment by ploeh** [comment]
In general, most test runners tend to suppress assembly binding problems, so in order to troubleshoot, it can be useful to try to run tests with the xUnit.net command-line runner.

**Comment by Thorium** [comment]
Thanks, you were correct! 
Now it's working with the latest components.

**Comment by ploeh** [comment]
Good to hear that you got it working :+1: 

The [presence of binaries in the repository is a deliberate choice](http://blog.ploeh.dk/2014/01/29/nuget-package-restore-considered-harmful), so this pull request represents a direction I don't wish to go. For that reason, I'm sure you'll understand that I'm declining the pull request.

If there's anything else I can help with, however, I'll be happy to do so.

**Comment by Thorium** [comment]
Ok, it's of course your decision completely and I respect that.

You probably know why reference components shouldn't be in version control, Git is not designed for binary files: 
- Text files in Git are stored only by the changeset, difference between the files. 
- Binary files are stored on each modification totally as new files. 
- Their version history will always stay, you can't delete it away from the repository, Git will keep every version in its repository, making your Git work slower and slower. 

Let's say that you want to keep FAKE up-to-date. Let's say that you use continuous integration and so does FAKE. The fake repository is 60MB and it has released 300 versions in last 2 years so your Git repository size would be 300x60 = 18GB just for FAKE components, then you have all the other binaries for all the other components. Needless to say this is not acceptable for any cloud-based Git-provider, but also, for enterprise Git if your repository is over a gigabyte it will start to get painful to use. And the clean-up maintenance without losing the whole history is not easy. 1GB is easy to achieve in enterprise development so even hundred of few megabyte binaries, or a few of hundred megabyte binaries, over a time will be problems.

In this kind of small example is fine, but in general I would like people to get to know the best practices in examples also.

**Comment by ploeh** [comment]
Why would I add _every_ version of FAKE to the repository?

**Comment by Thorium** [comment]
That was extreme example, but I have faced problems in real life within a few years with 80 components and "update about every two months"-policy (as security fixes etc. components should be quite up-to-date, there is usually a reason why a software package has a new version).

**Comment by ploeh** [comment]
I accept that an 18 GB repository is impractical. In reality, though, I haven't had issues with this policy.

As an example, [AutoFixture](https://github.com/AutoFixture/AutoFixture) is a fairly active project that's more than six years old, and the size of the repository is some 500 MB.

FWIW, here's a follup-up article that describes how I usually manage projects: http://blog.ploeh.dk/2014/02/03/using-nuget-with-autonomous-repositories

**Comment by Thorium** [comment]
"Active" OSS projects are still different activity level than e.g. financial enterprise applications, where are quite typical to have 100-500 developers doing actively code every day... But those developers also apply the principles they read from the internet, so your blog will be some kind of author. :-)

Not only that, by making your software updates harder (than with e.g. paket, which is a nice Nuget facade) you expose your software to security risks of known vulnerabilities of the underlying components. Nuget was quite young when you wrote your blog post and e.g. caching has improved. On the other hand merge conflict tools (that you will need when many software branches happen to update different 3rd party versions of components from your application with non-paket environment) have not improved so much. But of course software architectures are always like that, you pick your poison.

**Pull request closed without merging**
